version: '3.7'
services:
  postgresql:
    image: postgresql:12.0
    ports:
      - '3306:3306'
    volumes:
      - ./data:/var/lib/postgresql
    environment:
      - POSTGRES_RANDOM_ROOT_PASSWORD=yes
      - POSTGRES_DATABASE=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=9mREsvXDs9Gk89Ef
